using Quan_Ly_Nhan_Su.DTO;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Quan_Ly_Nhan_Su.BLL;

namespace Quan_Ly_Nhan_Su.GUI.LuongThuongUserControl
{
    public partial class LuongThuong : UserControl
    {
        private SalaryFullBLL salaryFullBLL = new SalaryFullBLL();
        private List<SalaryFullDTO> listSalaryFull;
        private BonusBLL bonusBLL = new BonusBLL();
        private List<BonusDTO> listBonus;
        private AllowanceDeductionBLL allowanceDeductionBLL = new AllowanceDeductionBLL();
        private List<AllowanceDeductionDTO> listAllowanceDeduction;
        private EmployeeBLL employeeBLL = new EmployeeBLL();
        private EmployeeFullBLL employeeFullBLL = new EmployeeFullBLL();
        private List<EmployeeFullDTO> listEmployee;
        private AttendanceBLL attendanceBLL = new AttendanceBLL();
        private PositionBLL positionBLL = new PositionBLL();

        private static readonly HashSet<string> _autoGeneratedMonths = new HashSet<string>();

        // Keep cached salary lists by month/year
        private List<SalaryFullDTO> currentMonthSalaries = new List<SalaryFullDTO>();

        public LuongThuong()
        {
            InitializeComponent();
            LoadEmployeeComboBox();
            ShowDataToTable();

            // Wire print/export button
            this.btnTinhLuong.Click += BtnTinhLuong_Click;

            // Wire back button if present
            if (this.btnBackToMonthly != null)
                this.btnBackToMonthly.Click += btnBackToMonthly_Click;

            // Fill monthly summary after loading data
            try
            {
                PopulateMonthlySummary();
                // start with monthly summary visible
                if (this.dataMonthlySummary != null && this.dataBangLuong != null && this.btnBackToMonthly != null)
                {
                    dataMonthlySummary.Visible = true;
                    dataBangLuong.Visible = false;
                    btnBackToMonthly.Visible = false;
                }
            }
            catch { /* ignore UI failures at startup */ }

            // Note: Auto-generate call removed to avoid background thread code if not present
        }

        private void BtnTinhLuong_Click(object sender, EventArgs e)
        {
            try
            {
                DataGridViewRow row = null;
                if (dataBangLuong.SelectedRows != null && dataBangLuong.SelectedRows.Count > 0)
                {
                    row = dataBangLuong.SelectedRows[0];
                }
                else if (dataBangLuong.CurrentRow != null)
                {
                    row = dataBangLuong.CurrentRow;
                }

                if (row == null)
                {
                    MessageBox.Show("Vui lòng chọn một nhân viên để xuất phiếu lương.", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }

                string maNhanVien = null;
                var colByName = dataBangLuong.Columns.Cast<DataGridViewColumn>()
                    .FirstOrDefault(c => string.Equals(c.Name, "MaNhanVien", StringComparison.OrdinalIgnoreCase) ||
                                         string.Equals(c.DataPropertyName, "MaNhanVien", StringComparison.OrdinalIgnoreCase) ||
                                         string.Equals(c.HeaderText, "Mã Nhân Viên", StringComparison.OrdinalIgnoreCase));

                if (colByName != null)
                {
                    maNhanVien = row.Cells[colByName.Index].Value?.ToString();
                }
                else if (row.Cells.Count > 1)
                {
                    maNhanVien = row.Cells[1]?.Value?.ToString();
                }

                if (string.IsNullOrWhiteSpace(maNhanVien))
                {
                    MessageBox.Show("Không lấy được mã nhân viên từ dòng đã chọn.", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    return;
                }

                using (var form = new BillFormGUI(maNhanVien))
                {
                    form.StartPosition = FormStartPosition.CenterParent;
                    form.ShowDialog(this);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Lỗi khi xuất phiếu lương: {ex.Message}", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void FillDataToBangLuongTable(List<SalaryFullDTO> listSalaryFull)
        {
            dataBangLuong.DataSource = null;
            dataBangLuong.DataSource = listSalaryFull;

            if (dataBangLuong.Columns.Contains("MaNhanVien")) dataBangLuong.Columns["MaNhanVien"].HeaderText = "Mã Nhân Viên";
            if (dataBangLuong.Columns.Contains("MaLuong")) dataBangLuong.Columns["MaLuong"].HeaderText = "Mã Lương";
            if (dataBangLuong.Columns.Contains("LuongCoBan")) dataBangLuong.Columns["LuongCoBan"].HeaderText = "Lương Cơ Bản";
            if (dataBangLuong.Columns.Contains("LuongTheoGio")) dataBangLuong.Columns["LuongTheoGio"].HeaderText = "Lương Theo Giờ";
            if (dataBangLuong.Columns.Contains("TongPhuCap")) dataBangLuong.Columns["TongPhuCap"].HeaderText = "Tổng Phụ Cấp";
            if (dataBangLuong.Columns.Contains("TongKhoanTru")) dataBangLuong.Columns["TongKhoanTru"].HeaderText = "Tổng Khoản Trừ";
            if (dataBangLuong.Columns.Contains("TongThuong")) dataBangLuong.Columns["TongThuong"].HeaderText = "Tổng Thưởng(%)";
            if (dataBangLuong.Columns.Contains("TongGioLam")) dataBangLuong.Columns["TongGioLam"].HeaderText = "Tổng Giờ Làm";
            if (dataBangLuong.Columns.Contains("LuongThucLanh")) dataBangLuong.Columns["LuongThucLanh"].HeaderText = "Lương Thực Lãnh";

            if (dataBangLuong.Columns.Contains("LuongCoBan")) dataBangLuong.Columns["LuongCoBan"].DefaultCellStyle.Format = "N0";
            if (dataBangLuong.Columns.Contains("LuongTheoGio")) dataBangLuong.Columns["LuongTheoGio"].DefaultCellStyle.Format = "N0";
            if (dataBangLuong.Columns.Contains("TongPhuCap")) dataBangLuong.Columns["TongPhuCap"].DefaultCellStyle.Format = "N0";
            if (dataBangLuong.Columns.Contains("TongKhoanTru")) dataBangLuong.Columns["TongKhoanTru"].DefaultCellStyle.Format = "N0";
            if (dataBangLuong.Columns.Contains("TongThuong")) dataBangLuong.Columns["TongThuong"].DefaultCellStyle.Format = "N0";
            if (dataBangLuong.Columns.Contains("LuongThucLanh")) dataBangLuong.Columns["LuongThucLanh"].DefaultCellStyle.Format = "N0";
            if (dataBangLuong.Columns.Contains("TongGioLam")) dataBangLuong.Columns["TongGioLam"].DefaultCellStyle.Format = "N2";

            dataBangLuong.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dataBangLuong.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        }

        private void FillDataToThuongTable(List<BonusDTO> listBonus)
        {
            dataThuong.DataSource = null;
            dataThuong.DataSource = listBonus;
            if (dataThuong.Columns.Contains("PhanTramThuong")) dataThuong.Columns["PhanTramThuong"].DefaultCellStyle.Format = "N0";
            dataThuong.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dataThuong.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        }

        private void FillDataToPCKTTable(List<AllowanceDeductionDTO> listAllowanceDeduction)
        {
            dataPCKT.DataSource = null;
            dataPCKT.DataSource = listAllowanceDeduction;
            if (dataPCKT.Columns.Contains("SoTien")) dataPCKT.Columns["SoTien"].DefaultCellStyle.Format = "N0";
            dataPCKT.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dataPCKT.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        }

        private void ShowDataToTable()
        {
            listSalaryFull = salaryFullBLL.GetAllSalaryFull();
            FillDataToBangLuongTable(listSalaryFull);
            listBonus = bonusBLL.GetAllBonuses();
            FillDataToThuongTable(listBonus);
            listAllowanceDeduction = allowanceDeductionBLL.GetAll();
            FillDataToPCKTTable(listAllowanceDeduction);
        }

        private void LoadEmployeeComboBox()
        {
            try
            {
                listEmployee = employeeFullBLL.GetAllEmployees();
                var list = listEmployee;
                cbThuong.DataSource = list;
                cbThuong.DisplayMember = "HoTen";
                cbThuong.ValueMember = "MaNhanVien";
                cbThuong.DropDownStyle = ComboBoxStyle.DropDownList;
                cbKT.DataSource = list;
                cbKT.DisplayMember = "HoTen";
                cbKT.ValueMember = "MaNhanVien";
                cbKT.DropDownStyle = ComboBoxStyle.DropDownList;
                cbPC.DataSource = list;
                cbPC.DisplayMember = "HoTen";
                cbPC.ValueMember = "MaNhanVien";
                cbPC.DropDownStyle = ComboBoxStyle.DropDownList;
            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi khi tải danh sách nhân viên: " + ex.Message);
            }
        }

        private void SearchData()
        {
            if (string.IsNullOrEmpty(tbSearch.Text))
            {
                dataBangLuong.DataSource = listSalaryFull;
                return;
            }

            string keyword = tbSearch.Text.Trim().ToLower();
            int thang = dateFilterThuong.Value.Month;
            int nam = dateFilterThuong.Value.Year;

            var filteredList = salaryFullBLL.GetSalaryFullByMonthYear(thang, nam)
                .Where(s => (s.MaNhanVien ?? "").ToLower().Contains(keyword) || (s.MaLuong ?? "").ToLower().Contains(keyword))
                .ToList();

            dataBangLuong.DataSource = null;
            dataBangLuong.DataSource = filteredList;
        }

        private void SearchThuongData()
        {
            if (string.IsNullOrEmpty(tbSearch2.Text))
            {
                dataThuong.DataSource = listBonus;
                return;
            }

            string keyword = tbSearch2.Text.Trim().ToLower();
            int thang = dateTimePicker2.Value.Month;
            int nam = dateTimePicker2.Value.Year;

            var filteredList = listBonus
                .Where(s => s.ThangApDung == thang && s.NamApDung == nam &&
                            ((s.MaNhanVien ?? "").ToLower().Contains(keyword) || s.MaThuong.ToString().Contains(keyword) || (s.TenThuong ?? "").ToLower().Contains(keyword)))
                .ToList();

            dataThuong.DataSource = null;
            dataThuong.DataSource = filteredList;
        }

        private void SearchPCKTData()
        {
            if (string.IsNullOrEmpty(tbLocPCKT.Text))
            {
                dataPCKT.DataSource = listAllowanceDeduction;
                return;
            }

            string keyword = tbLocPCKT.Text.Trim().ToLower();
            int thang = dateLocPCKT.Value.Month;
            int nam = dateLocPCKT.Value.Year;

            var filteredList = listAllowanceDeduction
                .Where(s => s.ThangApDung == thang && s.NamApDung == nam &&
                            ((s.MaNhanVien ?? "").ToLower().Contains(keyword) || s.MaPhuCapKhoanTru.ToString().Contains(keyword) || (s.MoTa ?? "").ToLower().Contains(keyword)))
                .ToList();

            dataPCKT.DataSource = null;
            dataPCKT.DataSource = filteredList;
        }

        private void PopulateMonthlySummary()
        {
            try
            {
                int year = DateTime.Now.Year;
                var summary = new List<dynamic>();

                for (int m = 1; m <= 12; m++)
                {
                    var salaries = salaryFullBLL.GetSalaryFullByMonthYear(m, year);
                    decimal total = salaries?.Sum(s => s.LuongThucLanh) ?? 0m;
                    // do not include a text 'Xem' property to avoid duplicate columns; we'll add a single button column below
                    summary.Add(new { Thang = m, Nam = year, TongLuong = total });
                }

                if (this.dataMonthlySummary != null)
                {
                    dataMonthlySummary.DataSource = null;
                    dataMonthlySummary.DataSource = summary;

                    // ensure columns auto-size to fill available width
                    dataMonthlySummary.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;

                    if (dataMonthlySummary.Columns.Contains("Thang")) dataMonthlySummary.Columns["Thang"].HeaderText = "Tháng";
                    if (dataMonthlySummary.Columns.Contains("Nam")) dataMonthlySummary.Columns["Nam"].Visible = false;
                    if (dataMonthlySummary.Columns.Contains("TongLuong")) {
                        dataMonthlySummary.Columns["TongLuong"].HeaderText = "Tổng Lương nhân viên trong tháng";
                        dataMonthlySummary.Columns["TongLuong"].DefaultCellStyle.Format = "N0";
                    }

                    // If a leftover text column named 'Xem' exists for any reason, remove it so only the button column remains
                    if (dataMonthlySummary.Columns.Contains("Xem"))
                    {
                        try { dataMonthlySummary.Columns.Remove("Xem"); } catch { }
                    }

                    if (!dataMonthlySummary.Columns.Contains("XemLink"))
                    {
                        var linkCol = new DataGridViewButtonColumn();
                        linkCol.Name = "XemLink";
                        linkCol.HeaderText = " ";
                        linkCol.Text = "Xem chi tiết";
                        linkCol.UseColumnTextForButtonValue = true;
                        // give the button column a reasonable fill weight
                        linkCol.FillWeight = 50; // smaller weight so amount gets more space
                        dataMonthlySummary.Columns.Add(linkCol);
                    }

                    // ensure the button column is last
                    dataMonthlySummary.Columns["XemLink"].DisplayIndex = dataMonthlySummary.Columns.Count - 1;

                    // tune column fill weights so TongLuong is wider
                    try
                    {
                        if (dataMonthlySummary.Columns.Contains("Thang")) dataMonthlySummary.Columns["Thang"].FillWeight = 30;
                        if (dataMonthlySummary.Columns.Contains("TongLuong")) dataMonthlySummary.Columns["TongLuong"].FillWeight = 200;
                        if (dataMonthlySummary.Columns.Contains("XemLink")) dataMonthlySummary.Columns["XemLink"].FillWeight = 50;
                    }
                    catch { }
                }
            }
            catch (Exception ex)
            {
                // don't block load; show optional error
                MessageBox.Show("Lỗi khi tạo bảng tổng hợp tháng: " + ex.Message, "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void dataMonthlySummary_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0) return;

            if (dataMonthlySummary.Columns[e.ColumnIndex] is DataGridViewButtonColumn || dataMonthlySummary.Columns[e.ColumnIndex].Name == "XemLink")
            {
                var row = dataMonthlySummary.Rows[e.RowIndex];
                int thang = Convert.ToInt32(row.Cells["Thang"].Value);
                int nam = DateTime.Now.Year;
                if (dataMonthlySummary.Columns.Contains("Nam"))
                {
                    int.TryParse(row.Cells["Nam"].Value?.ToString(), out nam);
                }

                currentMonthSalaries = salaryFullBLL.GetSalaryFullByMonthYear(thang, nam);
                dataBangLuong.DataSource = null;
                dataBangLuong.DataSource = currentMonthSalaries;
                FillDataToBangLuongTable(currentMonthSalaries);

                // switch views: hide monthly summary, show salary grid and back button
                if (this.dataMonthlySummary != null && this.dataBangLuong != null && this.btnBackToMonthly != null)
                {
                    dataMonthlySummary.Visible = false;
                    dataBangLuong.Visible = true;
                    btnBackToMonthly.Visible = true;
                    // clear selection for monthly summary
                    try { dataMonthlySummary.ClearSelection(); } catch { }
                }
            }
        }

        private void btnBackToMonthly_Click(object sender, EventArgs e)
        {
            try
            {
                // go back to monthly summary view
                if (this.dataMonthlySummary != null && this.dataBangLuong != null && this.btnBackToMonthly != null)
                {
                    dataMonthlySummary.Visible = true;
                    dataBangLuong.Visible = false;
                    btnBackToMonthly.Visible = false;

                    // restore monthly summary data
                    PopulateMonthlySummary();
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi khi quay lại: " + ex.Message, "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void dataThuong_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0) return;
            DataGridViewRow row = dataThuong.Rows[e.RowIndex];

            cbThuong.SelectedValue = row.Cells["MaNhanVien"].Value?.ToString();
            tbThuong.Text = row.Cells["TenThuong"].Value?.ToString();
            tbMucThuong.Text = row.Cells["PhanTramThuong"].Value?.ToString();
            int month = Convert.ToInt32(dataThuong.Rows[e.RowIndex].Cells["ThangApDung"].Value);
            int year = Convert.ToInt32(dataThuong.Rows[e.RowIndex].Cells["NamApDung"].Value);
            dateThuong.Value = new DateTime(year, month, 1);
        }

        private void dataPCKT_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0) return;
            DataGridViewRow row = dataPCKT.Rows[e.RowIndex];

            if (row.Cells["Loai"].Value?.ToString() == "PhuCap")
            {
                cbPC.SelectedValue = row.Cells["MaNhanVien"].Value?.ToString();
                tbNotePC.Text = row.Cells["MoTa"].Value?.ToString();
                tbSoTienPC.Text = row.Cells["SoTien"].Value?.ToString();
                int month = Convert.ToInt32(dataPCKT.Rows[e.RowIndex].Cells["ThangApDung"].Value);
                int year = Convert.ToInt32(dataPCKT.Rows[e.RowIndex].Cells["NamApDung"].Value);
                datePC.Value = new DateTime(year, month, 1);
            }
            else if (row.Cells["Loai"].Value?.ToString() == "KhoanTru")
            {
                cbKT.SelectedValue = row.Cells["MaNhanVien"].Value?.ToString();
                tbNoteKT.Text = row.Cells["MoTa"].Value?.ToString();
                tbSoTienKT.Text = row.Cells["SoTien"].Value?.ToString();
                int month = Convert.ToInt32(dataPCKT.Rows[e.RowIndex].Cells["ThangApDung"].Value);
                int year = Convert.ToInt32(dataPCKT.Rows[e.RowIndex].Cells["NamApDung"].Value);
                dateKT.Value = new DateTime(year, month, 1);
            }
        }

        private void btnLoc1_Click(object sender, EventArgs e)
        {
            int thang = dateFilterThuong.Value.Month;
            int nam = dateFilterThuong.Value.Year;

            var filteredList = salaryFullBLL.GetSalaryFullByMonthYear(thang, nam);
            dataBangLuong.DataSource = null;
            dataBangLuong.DataSource = filteredList;
        }

        private void btnSearch1_Click(object sender, EventArgs e)
        {
            SearchData();
        }

        private void btnLocThuong_Click(object sender, EventArgs e)
        {
            int thang = dateTimePicker2.Value.Month;
            int nam = dateTimePicker2.Value.Year;

            var filteredList = listBonus
                .Where(s => s.ThangApDung == thang && s.NamApDung == nam)
                .ToList();

            dataThuong.DataSource = null;
            dataThuong.DataSource = filteredList;
        }

        private void btnSearch2_Click(object sender, EventArgs e)
        {
            SearchThuongData();
        }

        private void btnThemThuong_Click(object sender, EventArgs e)
        {
            try
            {
                string maNV = cbThuong.SelectedValue?.ToString();
                string tenThuong = tbThuong.Text.Trim();
                decimal phanTram = decimal.Parse(tbMucThuong.Text.Trim());

                int thang = dateTimePicker2.Value.Month;
                int nam = dateTimePicker2.Value.Year;

                if (string.IsNullOrEmpty(maNV) || string.IsNullOrEmpty(tenThuong))
                {
                    MessageBox.Show("Vui lòng nhập đầy đủ thông tin!");
                    return;
                }

                BonusDTO bonus= new BonusDTO(maNV, tenThuong, phanTram, thang, nam);
                bool result = bonusBLL.AddBonus(bonus);

                if (result)
                {
                    MessageBox.Show("Thêm thưởng thành công!");
                    listBonus = bonusBLL.GetAllBonuses();
                    dataThuong.DataSource = null;
                    dataThuong.DataSource = listBonus;
                }    

                else
                    MessageBox.Show("Không thể thêm thưởng!");
            }
            catch (FormatException)
            {
                MessageBox.Show("Phần trăm thưởng phải là số hợp lệ!");
            }
        }

        private void label12_Click(object sender, EventArgs e)
        {

        }

        private void btnLocPCKT_Click(object sender, EventArgs e)
        {
            SearchPCKTData();
        }

        private void btnSearchPCKT_Click(object sender, EventArgs e)
        {
            int thang = dateLocPCKT.Value.Month;
            int nam = dateLocPCKT.Value.Year;

            var filteredList = listAllowanceDeduction
                .Where(s => s.ThangApDung == thang && s.NamApDung == nam)
                .ToList();

            dataPCKT.DataSource = null;
            dataPCKT.DataSource = filteredList;
        }

        private void btnPC_Click(object sender, EventArgs e)
        {
            try
            {
                string maNV = cbPC.SelectedValue?.ToString();
                string moTa = tbNotePC.Text.Trim();
                decimal soTien = decimal.Parse(tbSoTienPC.Text.Trim());

                int thang = datePC.Value.Month;
                int nam = datePC.Value.Year;
                string loai = "PhuCap";

                if (string.IsNullOrEmpty(maNV) || string.IsNullOrEmpty(moTa))
                {
                    MessageBox.Show("Vui lòng nhập đầy đủ thông tin!");
                    return;
                }

                AllowanceDeductionDTO pCKT = new AllowanceDeductionDTO(maNV, loai, moTa, soTien, thang, nam);
                bool result = allowanceDeductionBLL.Insert(pCKT);

                if (result)
                {
                    MessageBox.Show("Thêm phụ cấp thành công!");
                    listAllowanceDeduction = allowanceDeductionBLL.GetAll();
                    dataPCKT.DataSource = null;
                    dataPCKT.DataSource = listAllowanceDeduction;
                }

                else
                    MessageBox.Show("Không thể thêm phụ cấp!");
            }
            catch (FormatException)
            {
                MessageBox.Show("Số tiền phải là số hợp lệ!");
            }
        }

        private void btnKT_Click(object sender, EventArgs e)
        {
            try
            {
                string maNV = cbKT.SelectedValue?.ToString();
                string moTa = tbNoteKT.Text.Trim();
                decimal soTien = decimal.Parse(tbSoTienKT.Text.Trim());

                int thang = dateKT.Value.Month;
                int nam = dateKT.Value.Year;
                string loai = "KhoanTru";

                if (string.IsNullOrEmpty(maNV) || string.IsNullOrEmpty(moTa))
                {
                    MessageBox.Show("Vui lòng nhập đầy đủ thông tin!");
                    return;
                }

                AllowanceDeductionDTO pCKT = new AllowanceDeductionDTO(maNV, loai, moTa, soTien, thang, nam);
                bool result = allowanceDeductionBLL.Insert(pCKT);

                if (result)
                {
                    MessageBox.Show("Thêm khoản trừ thành công!");
                    listAllowanceDeduction = allowanceDeductionBLL.GetAll();
                    dataPCKT.DataSource = null;
                    dataPCKT.DataSource = listAllowanceDeduction;
                }

                else
                    MessageBox.Show("Không thể thêm khoản trừ!");
            }
            catch (FormatException)
            {
                MessageBox.Show("Số tiền phải là số hợp lệ!");
            }
        }

        private void dataThuong_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0) return;
            DataGridViewRow row = dataThuong.Rows[e.RowIndex];

            cbThuong.SelectedValue = row.Cells["MaNhanVien"].Value?.ToString();
            tbThuong.Text = row.Cells["TenThuong"].Value?.ToString();
            tbMucThuong.Text = row.Cells["PhanTramThuong"].Value?.ToString();
            int month = Convert.ToInt32(dataThuong.Rows[e.RowIndex].Cells["ThangApDung"].Value);
            int year = Convert.ToInt32(dataThuong.Rows[e.RowIndex].Cells["NamApDung"].Value);
            dateThuong.Value = new DateTime(year, month, 1);
        }

        private void dataPCKT_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0) return;
            DataGridViewRow row = dataPCKT.Rows[e.RowIndex];

            if (row.Cells["Loai"].Value?.ToString() == "PhuCap")
            {
                cbPC.SelectedValue = row.Cells["MaNhanVien"].Value?.ToString();
                tbNotePC.Text = row.Cells["MoTa"].Value?.ToString();
                tbSoTienPC.Text = row.Cells["SoTien"].Value?.ToString();
                int month = Convert.ToInt32(dataPCKT.Rows[e.RowIndex].Cells["ThangApDung"].Value);
                int year = Convert.ToInt32(dataPCKT.Rows[e.RowIndex].Cells["NamApDung"].Value);
                datePC.Value = new DateTime(year, month, 1);
            }
            else if (row.Cells["Loai"].Value?.ToString() == "KhoanTru")
            {
                cbKT.SelectedValue = row.Cells["MaNhanVien"].Value?.ToString();
                tbNoteKT.Text = row.Cells["MoTa"].Value?.ToString();
                tbSoTienKT.Text = row.Cells["SoTien"].Value?.ToString();
                int month = Convert.ToInt32(dataPCKT.Rows[e.RowIndex].Cells["ThangApDung"].Value);
                int year = Convert.ToInt32(dataPCKT.Rows[e.RowIndex].Cells["NamApDung"].Value);
                dateKT.Value = new DateTime(year, month, 1);
            }
        }

        private void btnCapNhatPCKT_Click(object sender, EventArgs e)
        {
            try
            {
                if (dataPCKT.CurrentRow == null)
                {
                    MessageBox.Show("Vui lòng chọn một dòng để cập nhật.", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }

                var row = dataPCKT.CurrentRow;
                int id = Convert.ToInt32(row.Cells["MaPhuCapKhoanTru"].Value);
                string loai = row.Cells["Loai"].Value?.ToString();

                string maNV = null;
                string moTa = null;
                decimal soTien = 0;
                int thang = 0;
                int nam = 0;

                if (string.Equals(loai, "PhuCap", StringComparison.OrdinalIgnoreCase))
                {
                    maNV = cbPC.SelectedValue?.ToString();
                    moTa = tbNotePC.Text.Trim();
                    if (!decimal.TryParse(tbSoTienPC.Text.Trim(), out soTien))
                    {
                        MessageBox.Show("Số tiền phải là số hợp lệ!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        return;
                    }
                    thang = datePC.Value.Month;
                    nam = datePC.Value.Year;
                }
                else
                {
                    maNV = cbKT.SelectedValue?.ToString();
                    moTa = tbNoteKT.Text.Trim();
                    if (!decimal.TryParse(tbSoTienKT.Text.Trim(), out soTien))
                    {
                        MessageBox.Show("Số tiền phải là số hợp lệ!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        return;
                    }
                    thang = dateKT.Value.Month;
                    nam = dateKT.Value.Year;
                }

                AllowanceDeductionDTO dto = new AllowanceDeductionDTO(maNV, loai, moTa, soTien, thang, nam);
                dto.MaPhuCapKhoanTru = id;

                bool result = allowanceDeductionBLL.Update(dto);
                if (result)
                {
                    MessageBox.Show("Cập nhật thành công!", "Thành công", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    listAllowanceDeduction = allowanceDeductionBLL.GetAll();
                    dataPCKT.DataSource = null;
                    dataPCKT.DataSource = listAllowanceDeduction;
                }
                else
                {
                    MessageBox.Show("Cập nhật thất bại!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi khi cập nhật PCKT: " + ex.Message, "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btnCapNhatThuong_Click(object sender, EventArgs e)
        {
            try
            {
                if (dataThuong.CurrentRow == null)
                {
                    MessageBox.Show("Vui lòng chọn một dòng để cập nhật.", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }

                var row = dataThuong.CurrentRow;
                int maThuong = Convert.ToInt32(row.Cells["MaThuong"].Value);

                string maNV = cbThuong.SelectedValue?.ToString();
                string tenThuong = tbThuong.Text.Trim();
                decimal phanTram;
                if (!decimal.TryParse(tbMucThuong.Text.Trim(), out phanTram))
                {
                    MessageBox.Show("Phần trăm thưởng phải là số hợp lệ!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    return;
                }

                int thang = dateThuong.Value.Month;
                int nam = dateThuong.Value.Year;

                BonusDTO bonus = new BonusDTO(maNV, tenThuong, phanTram, thang, nam);
                bonus.MaThuong = maThuong;

                bool result = bonusBLL.UpdateBonus(bonus);
                if (result)
                {
                    MessageBox.Show("Cập nhật thưởng thành công!", "Thành công", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    listBonus = bonusBLL.GetAllBonuses();
                    dataThuong.DataSource = null;
                    dataThuong.DataSource = listBonus;
                }
                else
                {
                    MessageBox.Show("Cập nhật thưởng thất bại!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi khi cập nhật thưởng: " + ex.Message, "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btnCapNhatPC_Click(object sender, EventArgs e)
        {
            try
            {
                if (dataPCKT.CurrentRow == null)
                {
                    MessageBox.Show("Vui lòng chọn một dòng để cập nhật.", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }

                var row = dataPCKT.CurrentRow;
                int id = Convert.ToInt32(row.Cells["MaPhuCapKhoanTru"].Value);
                string loai = row.Cells["Loai"].Value?.ToString();

                string maNV = null;
                string moTa = null;
                decimal soTien = 0;
                int thang = 0;
                int nam = 0;

                maNV = cbPC.SelectedValue?.ToString();
                moTa = tbNotePC.Text.Trim();
                if (!decimal.TryParse(tbSoTienPC.Text.Trim(), out soTien))
                {
                    MessageBox.Show("Số tiền phải là số hợp lệ!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    return;
                }
                thang = datePC.Value.Month;
                nam = datePC.Value.Year;

                AllowanceDeductionDTO dto = new AllowanceDeductionDTO(maNV, loai, moTa, soTien, thang, nam);
                dto.MaPhuCapKhoanTru = id;

                bool result = allowanceDeductionBLL.Update(dto);
                if (result)
                {
                    MessageBox.Show("Cập nhật thành công!", "Thành công", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    listAllowanceDeduction = allowanceDeductionBLL.GetAll();
                    dataPCKT.DataSource = null;
                    dataPCKT.DataSource = listAllowanceDeduction;
                }
                else
                {
                    MessageBox.Show("Cập nhật thất bại!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi khi cập nhật PCKT: " + ex.Message, "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btnCapNhatKT_Click(object sender, EventArgs e)
        {
            try
            {
                if (dataPCKT.CurrentRow == null)
                {
                    MessageBox.Show("Vui lòng chọn một dòng để cập nhật.", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }

                var row = dataPCKT.CurrentRow;
                int id = Convert.ToInt32(row.Cells["MaPhuCapKhoanTru"].Value);
                string loai = row.Cells["Loai"].Value?.ToString();

                string maNV = null;
                string moTa = null;
                decimal soTien = 0;
                int thang = 0;
                int nam = 0;

                maNV = cbPC.SelectedValue?.ToString();
                moTa = tbNotePC.Text.Trim();
                if (!decimal.TryParse(tbSoTienPC.Text.Trim(), out soTien))
                {
                    MessageBox.Show("Số tiền phải là số hợp lệ!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    return;
                }
                thang = datePC.Value.Month;
                nam = datePC.Value.Year;

                AllowanceDeductionDTO dto = new AllowanceDeductionDTO(maNV, loai, moTa, soTien, thang, nam);
                dto.MaPhuCapKhoanTru = id;

                bool result = allowanceDeductionBLL.Update(dto);
                if (result)
                {
                    MessageBox.Show("Cập nhật thành công!", "Thành công", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    listAllowanceDeduction = allowanceDeductionBLL.GetAll();
                    dataPCKT.DataSource = null;
                    dataPCKT.DataSource = listAllowanceDeduction;
                }
                else
                {
                    MessageBox.Show("Cập nhật thất bại!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi khi cập nhật PCKT: " + ex.Message, "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btnResetThuong_Click(object sender, EventArgs e)
        {
            try
            {
                tbThuong.Text = string.Empty;
                tbMucThuong.Text = string.Empty;

                var now = DateTime.Now;
                dateThuong.Value = new DateTime(now.Year, now.Month, 1);

                try
                {
                    cbThuong.SelectedIndex = -1;
                }
                catch
                {
                    cbThuong.SelectedItem = null;
                }
                if (dataThuong.SelectedRows != null && dataThuong.SelectedRows.Count > 0)
                    dataThuong.ClearSelection();
                if (dataThuong.CurrentCell != null)
                    dataThuong.CurrentCell = null;
            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi khi reset form thưởng: " + ex.Message, "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btnResetPCKT_Click(object sender, EventArgs e)
        {
            try
            {
                tbSoTienPC.Text = string.Empty;
                tbNotePC.Text = string.Empty;
                var now = DateTime.Now;
                datePC.Value = new DateTime(now.Year, now.Month, 1);
                try
                {
                    cbPC.SelectedIndex = -1;
                }
                catch
                {
                    cbPC.SelectedItem = null;
                }

                tbSoTienKT.Text = string.Empty;
                tbNoteKT.Text = string.Empty;
                dateKT.Value = new DateTime(now.Year, now.Month, 1);
                try
                {
                    cbKT.SelectedIndex = -1;
                }
                catch
                {
                    cbKT.SelectedItem = null;
                }

                if (dataPCKT.SelectedRows != null && dataPCKT.SelectedRows.Count > 0)
                    dataPCKT.ClearSelection();
                if (dataPCKT.CurrentCell != null)
                    dataPCKT.CurrentCell = null;
            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi khi reset form Phụ cấp/Khoản trừ: " + ex.Message, "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private async void AutoGenerateForCurrentMonthIfNeeded()
        {
            string key = DateTime.Now.ToString("yyyyMM");
            if (_autoGeneratedMonths.Contains(key))
                return;

            _autoGeneratedMonths.Add(key);

            int month = DateTime.Now.Month;
            int year = DateTime.Now.Year;

            try
            {
                var result = await Task.Run(() => GenerateAutoAllowancesAndDeductionsInternal(month, year));

                listAllowanceDeduction = allowanceDeductionBLL.GetAll();
                if (this.IsHandleCreated)
                {
                    this.Invoke((Action)(() =>
                    {
                        dataPCKT.DataSource = null;
                        dataPCKT.DataSource = listAllowanceDeduction;
                        MessageBox.Show($"Auto generation done. Inserted: {result.inserted}, Skipped(existing): {result.skipped}", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    }));
                }
            }
            catch (Exception ex)
            {
                if (this.IsHandleCreated)
                {
                    this.Invoke((Action)(() =>
                    {
                        MessageBox.Show("Lỗi khi tạo tự động PCKT/thuế: " + ex.Message, "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }));
                }
            }
        }

        private (int inserted, int skipped) GenerateAutoAllowancesAndDeductionsInternal(int month, int year)
        {
            if (month < 1 || month > 12) throw new ArgumentOutOfRangeException(nameof(month));
            if (year < 2000 || year > 2100) throw new ArgumentOutOfRangeException(nameof(year));

            int inserted = 0;
            int skipped = 0;
            const int perMinutePenalty = 2000;

            var employees = employeeFullBLL.GetAllEmployees();
            var existingPCKT = allowanceDeductionBLL.GetAll();

            foreach (var emp in employees)
            {
                if (string.IsNullOrWhiteSpace(emp.MaNhanVien)) continue;

                string empPositionId = employeeBLL.GetEmp(emp.MaNhanVien).MaChucVu;
                decimal positionPercent = positionBLL.GetPosition(empPositionId).PhuCapChucVu;
                if (positionPercent > 0 && emp.MucLuong > 0)
                {
                    bool exists = existingPCKT.Any(x =>
                        x.MaNhanVien == emp.MaNhanVien &&
                        string.Equals(x.Loai, "PhuCap", StringComparison.OrdinalIgnoreCase) &&
                        string.Equals(x.MoTa, "Phu cấp chức vụ", StringComparison.OrdinalIgnoreCase) &&
                        x.ThangApDung == month && x.NamApDung == year);

                    if (!exists)
                    {
                        var dto = new AllowanceDeductionDTO(emp.MaNhanVien, "PhuCap", "Phu cấp chức vụ", positionPercent, month, year);
                        if (allowanceDeductionBLL.Insert(dto))
                        {
                            inserted++;
                            existingPCKT.Add(dto);
                        }
                    }
                    else skipped++;
                }

                decimal taxAmount = Math.Round(emp.MucLuong * 0.05m, 0);
                bool taxExists = existingPCKT.Any(x =>
                    x.MaNhanVien == emp.MaNhanVien &&
                    string.Equals(x.Loai, "KhoanTru", StringComparison.OrdinalIgnoreCase) &&
                    string.Equals(x.MoTa, "Thuế TNCN 5%", StringComparison.OrdinalIgnoreCase) &&
                    x.ThangApDung == month && x.NamApDung == year);

                if (!taxExists && taxAmount > 0)
                {
                    var taxDto = new AllowanceDeductionDTO(emp.MaNhanVien, "KhoanTru", "Thuế TNCN 5%", taxAmount, month, year);
                    if (allowanceDeductionBLL.Insert(taxDto))
                    {
                        inserted++;
                        existingPCKT.Add(taxDto);
                    }
                }
                else if (taxExists) skipped++;

                var attendanceTotal = attendanceBLL.calculateTotalOfMonth(emp.MaNhanVien, month, year);
                int totalMinutesLateEarly = (attendanceTotal?.GoLate ?? 0) + (attendanceTotal?.LeaveEarly ?? 0);

                if (totalMinutesLateEarly > 0)
                {
                    decimal deductionAmount = Math.Round(totalMinutesLateEarly * (decimal)perMinutePenalty, 0);

                    bool existsLateEarly = existingPCKT.Any(x =>
                        x.MaNhanVien == emp.MaNhanVien &&
                        string.Equals(x.Loai, "KhoanTru", StringComparison.OrdinalIgnoreCase) &&
                        x.MoTa != null &&
                        x.MoTa.StartsWith("Trừ trễ/về sớm", StringComparison.OrdinalIgnoreCase) &&
                        x.ThangApDung == month && x.NamApDung == year);

                    if (!existsLateEarly && deductionAmount > 0)
                    {
                        var absDto = new AllowanceDeductionDTO(emp.MaNhanVien, "KhoanTru", $"Trừ trễ/về sớm ({totalMinutesLateEarly} phút)", deductionAmount, month, year);
                        if (allowanceDeductionBLL.Insert(absDto))
                        {
                            inserted++;
                            existingPCKT.Add(absDto);
                        }
                    }
                    else skipped++;
                }

            }

            return (inserted, skipped);
        }
        // Designer-event stubs (no-op) to satisfy designer wiring
        private void tableLayoutPanel1_Paint(object sender, PaintEventArgs e) { }
        private void textBox1_TextChanged(object sender, EventArgs e) { }
        private void tableLayoutPanel3_Paint(object sender, PaintEventArgs e) { }
        private void comboBox13_SelectedIndexChanged(object sender, EventArgs e) { }
        private void label6_Click(object sender, EventArgs e) { }
        private void btnCapNhatThuong_Click(object sender, EventArgs e) { /* may be implemented later */ }
        private void label18_Click(object sender, EventArgs e) { }
        private void btnCapNhatPC_Click(object sender, EventArgs e) { /* may be implemented later */ }
        private void btnCapNhatKT_Click(object sender, EventArgs e) { /* may be implemented later */ }
        private void btnResetThuong_Click(object sender, EventArgs e) { /* reset handled elsewhere */ }
        private void btnResetPCKT_Click(object sender, EventArgs e) { /* reset handled elsewhere */ }
    }
}
