using Quan_Ly_Nhan_Su.DTO;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Quan_Ly_Nhan_Su.BLL;
using Quan_Ly_Nhan_Su.GUI; // for BillFormGUI

namespace Quan_Ly_Nhan_Su.GUI.LuongThuongUserControl
{
    public partial class LuongThuong : UserControl
    {
        private SalaryFullBLL salaryFullBLL = new SalaryFullBLL();
        private List<SalaryFullDTO> listSalaryFull;
        private BonusBLL bonusBLL = new BonusBLL();
        private List<BonusDTO> listBonus;
        private AllowanceDeductionBLL allowanceDeductionBLL = new AllowanceDeductionBLL();
        private List<AllowanceDeductionDTO> listAllowanceDeduction;
        private EmployeeFullBLL employeeFullBLL = new EmployeeFullBLL();
        private List<EmployeeFullDTO> listEmployee;
        private AttendanceBLL attendanceBLL = new AttendanceBLL();

        private static readonly HashSet<string> _autoGeneratedMonths = new HashSet<string>();

        public LuongThuong()
        {
            InitializeComponent();
            LoadEmployeeComboBox();
            ShowDataToTable();

            // Wire print/export button
            this.btnTinhLuong.Click += BtnTinhLuong_Click;

            // Automatically generate allowances/deductions for the current month once per app session
            AutoGenerateForCurrentMonthIfNeeded();
        }

        private void BtnTinhLuong_Click(object sender, EventArgs e)
        {
            try
            {
                // Ensure a row is selected
                DataGridViewRow row = null;
                if (dataBangLuong.SelectedRows != null && dataBangLuong.SelectedRows.Count > 0)
                {
                    row = dataBangLuong.SelectedRows[0];
                }
                else if (dataBangLuong.CurrentRow != null)
                {
                    row = dataBangLuong.CurrentRow;
                }

                if (row == null)
                {
                    MessageBox.Show("Vui lòng chọn một nhân viên để xuất phiếu lương.", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }

                string maNhanVien = null;
                // Prefer column with Name or DataPropertyName 'MaNhanVien'
                var colByName = dataBangLuong.Columns.Cast<DataGridViewColumn>()
                    .FirstOrDefault(c => string.Equals(c.Name, "MaNhanVien", StringComparison.OrdinalIgnoreCase) ||
                                         string.Equals(c.DataPropertyName, "MaNhanVien", StringComparison.OrdinalIgnoreCase) ||
                                         string.Equals(c.HeaderText, "Mã Nhân Viên", StringComparison.OrdinalIgnoreCase));

                if (colByName != null)
                {
                    maNhanVien = row.Cells[colByName.Index].Value?.ToString();
                }
                else if (row.Cells.Count > 1)
                {
                    // fallback to second cell which typically holds MaNhanVien in the grid screenshot
                    maNhanVien = row.Cells[1]?.Value?.ToString();
                }

                if (string.IsNullOrWhiteSpace(maNhanVien))
                {
                    MessageBox.Show("Không lấy được mã nhân viên từ dòng đã chọn.", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    return;
                }

                // Open BillFormGUI with the selected employee code
                using (var form = new BillFormGUI(maNhanVien))
                {
                    form.StartPosition = FormStartPosition.CenterParent;
                    form.ShowDialog(this);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Lỗi khi xuất phiếu lương: {ex.Message}", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void FillDataToBangLuongTable(List<SalaryFullDTO> listSalaryFull)
        {
            dataBangLuong.DataSource = null;
            dataBangLuong.DataSource = listSalaryFull;

            dataBangLuong.Columns["MaNhanVien"].HeaderText = "Mã Nhân Viên";
            dataBangLuong.Columns["MaLuong"].HeaderText = "Mã Lương";
            dataBangLuong.Columns["LuongCoBan"].HeaderText = "Lương Cơ Bản";
            dataBangLuong.Columns["LuongTheoGio"].HeaderText = "Lương Theo Giờ";
            dataBangLuong.Columns["TongPhuCap"].HeaderText = "Tổng Phụ Cấp";
            dataBangLuong.Columns["TongKhoanTru"].HeaderText = "Tổng Khoản Trừ";
            dataBangLuong.Columns["TongThuong"].HeaderText = "Tổng Thưởng(%)";
            dataBangLuong.Columns["TongGioLam"].HeaderText = "Tổng Giờ Làm";
            dataBangLuong.Columns["LuongThucLanh"].HeaderText = "Lương Thực Lãnh";

            dataBangLuong.Columns["LuongCoBan"].DefaultCellStyle.Format = "N0";
            dataBangLuong.Columns["LuongTheoGio"].DefaultCellStyle.Format = "N0";
            dataBangLuong.Columns["TongPhuCap"].DefaultCellStyle.Format = "N0";
            dataBangLuong.Columns["TongKhoanTru"].DefaultCellStyle.Format = "N0";
            dataBangLuong.Columns["TongThuong"].DefaultCellStyle.Format = "N0";
            dataBangLuong.Columns["LuongThucLanh"].DefaultCellStyle.Format = "N0";

            dataBangLuong.Columns["TongGioLam"].DefaultCellStyle.Format = "N2";

            dataBangLuong.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dataBangLuong.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        }

        private void FillDataToThuongTable(List<BonusDTO> listBonus)
        {
            dataThuong.DataSource = null;
            dataThuong.DataSource = listBonus;
            dataThuong.Columns["MaThuong"].HeaderText = "Mã Thưởng";
            dataThuong.Columns["MaNhanVien"].HeaderText = "Mã Nhân Viên";
            dataThuong.Columns["TenThuong"].HeaderText = "Tên Thưởng";
            dataThuong.Columns["PhanTramThuong"].HeaderText = "Phần trăm thưởng";
            dataThuong.Columns["ThangApDung"].HeaderText = "ThanhApDung";
            dataThuong.Columns["NamApDung"].HeaderText = "NamApDung";

            dataThuong.Columns["PhanTramThuong"].DefaultCellStyle.Format = "N0";

            dataThuong.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dataThuong.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        }

        private void FillDataToPCKTTable(List<AllowanceDeductionDTO> listAllowanceDeduction)
        {
            dataPCKT.DataSource = null;
            dataPCKT.DataSource = listAllowanceDeduction;
            dataPCKT.Columns["MaPhuCapKhoanTru"].HeaderText = "Mã PCKT";
            dataPCKT.Columns["MaNhanVien"].HeaderText = "Mã Nhân Viên";
            dataPCKT.Columns["Loai"].HeaderText = "Loại";
            dataPCKT.Columns["MoTa"].HeaderText = "Mô Tả";
            dataPCKT.Columns["SoTien"].HeaderText = "Số Tiền";
            dataPCKT.Columns["ThangApDung"].HeaderText = "Tháng Áp Dụng";
            dataPCKT.Columns["NamApDung"].HeaderText = "Năm Áp Dụng";

            dataPCKT.Columns["SoTien"].DefaultCellStyle.Format = "N0";

            dataPCKT.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dataPCKT.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        }

        private void ShowDataToTable()
        {
            listSalaryFull = salaryFullBLL.GetAllSalaryFull();
            FillDataToBangLuongTable(listSalaryFull);
            listBonus = bonusBLL.GetAllBonuses();
            FillDataToThuongTable(listBonus);
            listAllowanceDeduction = allowanceDeductionBLL.GetAll(); 
            FillDataToPCKTTable(listAllowanceDeduction);
        }

        private void LoadEmployeeComboBox()
        {
            try
            {
                listEmployee = employeeFullBLL.GetAllEmployees();
                var list = listEmployee;
                cbThuong.DataSource = list;
                cbThuong.DisplayMember = "HoTen";
                cbThuong.ValueMember = "MaNhanVien";
                cbThuong.DropDownStyle = ComboBoxStyle.DropDownList;
                cbKT.DataSource = list;
                cbKT.DisplayMember = "HoTen";
                cbKT.ValueMember = "MaNhanVien";
                cbKT.DropDownStyle = ComboBoxStyle.DropDownList;
                cbPC.DataSource = list;
                cbPC.DisplayMember = "HoTen";
                cbPC.ValueMember = "MaNhanVien";
                cbPC.DropDownStyle = ComboBoxStyle.DropDownList;
            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi khi tải danh sách nhân viên: " + ex.Message);
            }
        }

        private void SearchData()
        {
            if(tbSearch.Text == null)
            {
                dataBangLuong.DataSource = null;
                dataBangLuong.DataSource = listSalaryFull;
            } else
            {
                string keyword = tbSearch.Text.Trim().ToLower();
                int thang = dateFilterThuong.Value.Month;
                int nam = dateFilterThuong.Value.Year;

                var filteredList = salaryFullBLL.GetSalaryFullByMonthYear(thang, nam)
                    .Where(s =>
                        (s.MaNhanVien.ToLower().Contains(keyword) ||
                         s.MaLuong.ToLower().Contains(keyword)))
                    .ToList();

                dataBangLuong.DataSource = null;
                dataBangLuong.DataSource = filteredList;
            }
        }

        private void SearchThuongData()
        {
            if (tbSearch2.Text == null)
            {
                dataThuong.DataSource = null;
                dataThuong.DataSource = listBonus;
            }
            else
            {
                string keyword = tbSearch2.Text.Trim().ToLower();
                int thang = dateTimePicker2.Value.Month;
                int nam = dateTimePicker2.Value.Year;

                var filteredList = listBonus
                    .Where(s =>
                        (s.ThangApDung == thang && s.NamApDung == nam) &&
                        (s.MaNhanVien.ToLower().Contains(keyword) ||
                        s.MaThuong.ToString().Contains(keyword) ||
                        s.TenThuong.ToLower().Contains(keyword)))
                    .ToList();

                dataThuong.DataSource = null;
                dataThuong.DataSource = filteredList;
            }
        }

        private void SearchPCKTData()
        {
            if (tbLocPCKT.Text == null)
            {
                dataPCKT.DataSource = null;
                dataPCKT.DataSource = listAllowanceDeduction;
            }
            else
            {
                string keyword = tbLocPCKT.Text.Trim().ToLower();
                int thang = dateLocPCKT.Value.Month;
                int nam = dateLocPCKT.Value.Year;

                var filteredList = listAllowanceDeduction
                    .Where(s =>
                        (s.ThangApDung == thang && s.NamApDung == nam) &&
                        (s.MaNhanVien.ToLower().Contains(keyword) ||
                        s.MaPhuCapKhoanTru.ToString().Contains(keyword) ||
                        s.MoTa.ToLower().Contains(keyword)))
                    .ToList();

                dataPCKT.DataSource = null;
                dataPCKT.DataSource = filteredList;
            }
        }

        private void tabControl2_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        private void textBox1_TextChanged(object sender, EventArgs e)
        {

        }

        private void tableLayoutPanel1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void dataGridView1_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {

        }

        private void tableLayoutPanel3_Paint(object sender, PaintEventArgs e)
        {

        }

        private void comboBox14_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        private void tableLayoutPanel11_Paint(object sender, PaintEventArgs e)
        {

        }

        private void label16_Click(object sender, EventArgs e)
        {

        }

        private void label18_Click(object sender, EventArgs e)
        {

        }

        private void label6_Click(object sender, EventArgs e)
        {

        }

        private void comboBox13_SelectedIndexChanged(object sender, EventArgs e)
        {
        
        }

        private void btnLoc1_Click(object sender, EventArgs e)
        {
            int thang = dateFilterThuong.Value.Month;
            int nam = dateFilterThuong.Value.Year;

            var filteredList = salaryFullBLL.GetSalaryFullByMonthYear(thang, nam);
            dataBangLuong.DataSource = null;
            dataBangLuong.DataSource = filteredList;
        }

        private void btnSearch1_Click(object sender, EventArgs e)
        {
            SearchData();
        }

        private void btnLocThuong_Click(object sender, EventArgs e)
        {
            int thang = dateTimePicker2.Value.Month;
            int nam = dateTimePicker2.Value.Year;

            var filteredList = listBonus
                .Where(s => s.ThangApDung == thang && s.NamApDung == nam)
                .ToList();

            dataThuong.DataSource = null;
            dataThuong.DataSource = filteredList;
        }

        private void btnSearch2_Click(object sender, EventArgs e)
        {
            SearchThuongData();
        }

        private void btnThemThuong_Click(object sender, EventArgs e)
        {
            try
            {
                string maNV = cbThuong.SelectedValue?.ToString();
                string tenThuong = tbThuong.Text.Trim();
                decimal phanTram = decimal.Parse(tbMucThuong.Text.Trim());

                int thang = dateTimePicker2.Value.Month;
                int nam = dateTimePicker2.Value.Year;

                if (string.IsNullOrEmpty(maNV) || string.IsNullOrEmpty(tenThuong))
                {
                    MessageBox.Show("Vui lòng nhập đầy đủ thông tin!");
                    return;
                }

                BonusDTO bonus= new BonusDTO(maNV, tenThuong, phanTram, thang, nam);
                bool result = bonusBLL.AddBonus(bonus);

                if (result)
                {
                    MessageBox.Show("Thêm thưởng thành công!");
                    listBonus = bonusBLL.GetAllBonuses();
                    dataThuong.DataSource = null;
                    dataThuong.DataSource = listBonus;
                }    

                else
                    MessageBox.Show("Không thể thêm thưởng!");
            }
            catch (FormatException)
            {
                MessageBox.Show("Phần trăm thưởng phải là số hợp lệ!");
            }
        }

        private void label12_Click(object sender, EventArgs e)
        {

        }

        private void btnLocPCKT_Click(object sender, EventArgs e)
        {
            SearchPCKTData();
        }

        private void btnSearchPCKT_Click(object sender, EventArgs e)
        {
            int thang = dateLocPCKT.Value.Month;
            int nam = dateLocPCKT.Value.Year;

            var filteredList = listAllowanceDeduction
                .Where(s => s.ThangApDung == thang && s.NamApDung == nam)
                .ToList();

            dataPCKT.DataSource = null;
            dataPCKT.DataSource = filteredList;
        }

        private void btnPC_Click(object sender, EventArgs e)
        {
            try
            {
                string maNV = cbPC.SelectedValue?.ToString();
                string moTa = tbNotePC.Text.Trim();
                decimal soTien = decimal.Parse(tbSoTienPC.Text.Trim());

                int thang = datePC.Value.Month;
                int nam = datePC.Value.Year;
                string loai = "PhuCap";

                if (string.IsNullOrEmpty(maNV) || string.IsNullOrEmpty(moTa))
                {
                    MessageBox.Show("Vui lòng nhập đầy đủ thông tin!");
                    return;
                }

                AllowanceDeductionDTO pCKT = new AllowanceDeductionDTO(maNV, loai, moTa, soTien, thang, nam);
                bool result = allowanceDeductionBLL.Insert(pCKT);

                if (result)
                {
                    MessageBox.Show("Thêm phụ cấp thành công!");
                    listAllowanceDeduction = allowanceDeductionBLL.GetAll();
                    dataPCKT.DataSource = null;
                    dataPCKT.DataSource = listAllowanceDeduction;
                }

                else
                    MessageBox.Show("Không thể thêm phụ cấp!");
            }
            catch (FormatException)
            {
                MessageBox.Show("Số tiền phải là số hợp lệ!");
            }
        }

        private void btnKT_Click(object sender, EventArgs e)
        {
            try
            {
                string maNV = cbKT.SelectedValue?.ToString();
                string moTa = tbNoteKT.Text.Trim();
                decimal soTien = decimal.Parse(tbSoTienKT.Text.Trim());

                int thang = dateKT.Value.Month;
                int nam = dateKT.Value.Year;
                string loai = "KhoanTru";

                if (string.IsNullOrEmpty(maNV) || string.IsNullOrEmpty(moTa))
                {
                    MessageBox.Show("Vui lòng nhập đầy đủ thông tin!");
                    return;
                }

                AllowanceDeductionDTO pCKT = new AllowanceDeductionDTO(maNV, loai, moTa, soTien, thang, nam);
                bool result = allowanceDeductionBLL.Insert(pCKT);

                if (result)
                {
                    MessageBox.Show("Thêm khoản trừ thành công!");
                    listAllowanceDeduction = allowanceDeductionBLL.GetAll();
                    dataPCKT.DataSource = null;
                    dataPCKT.DataSource = listAllowanceDeduction;
                }

                else
                    MessageBox.Show("Không thể thêm khoản trừ!");
            }
            catch (FormatException)
            {
                MessageBox.Show("Số tiền phải là số hợp lệ!");
            }
        }

        private void dataThuong_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0) return;
            DataGridViewRow row = dataThuong.Rows[e.RowIndex];

            cbThuong.SelectedValue = row.Cells["MaNhanVien"].Value?.ToString();
            tbThuong.Text = row.Cells["TenThuong"].Value?.ToString();
            tbMucThuong.Text = row.Cells["PhanTramThuong"].Value?.ToString();
            int month = Convert.ToInt32(dataThuong.Rows[e.RowIndex].Cells["ThangApDung"].Value);
            int year = Convert.ToInt32(dataThuong.Rows[e.RowIndex].Cells["NamApDung"].Value);
            dateThuong.Value = new DateTime(year, month, 1);
        }

        private void dataPCKT_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0) return;
            DataGridViewRow row = dataPCKT.Rows[e.RowIndex];

            if (row.Cells["Loai"].Value?.ToString() == "PhuCap")
            {
                cbPC.SelectedValue = row.Cells["MaNhanVien"].Value?.ToString();
                tbNotePC.Text = row.Cells["MoTa"].Value?.ToString();
                tbSoTienPC.Text = row.Cells["SoTien"].Value?.ToString();
                int month = Convert.ToInt32(dataPCKT.Rows[e.RowIndex].Cells["ThangApDung"].Value);
                int year = Convert.ToInt32(dataPCKT.Rows[e.RowIndex].Cells["NamApDung"].Value);
                datePC.Value = new DateTime(year, month, 1);
            }
            else if (row.Cells["Loai"].Value?.ToString() == "KhoanTru")
            {
                cbKT.SelectedValue = row.Cells["MaNhanVien"].Value?.ToString();
                tbNoteKT.Text = row.Cells["MoTa"].Value?.ToString();
                tbSoTienKT.Text = row.Cells["SoTien"].Value?.ToString();
                int month = Convert.ToInt32(dataPCKT.Rows[e.RowIndex].Cells["ThangApDung"].Value);
                int year = Convert.ToInt32(dataPCKT.Rows[e.RowIndex].Cells["NamApDung"].Value);
                dateKT.Value = new DateTime(year, month, 1);
            }
        }

        private void btnCapNhatPCKT_Click(object sender, EventArgs e)
        {
            try
            {
                if (dataPCKT.CurrentRow == null)
                {
                    MessageBox.Show("Vui lòng chọn một dòng để cập nhật.", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }

                var row = dataPCKT.CurrentRow;
                int id = Convert.ToInt32(row.Cells["MaPhuCapKhoanTru"].Value);
                string loai = row.Cells["Loai"].Value?.ToString();

                string maNV = null;
                string moTa = null;
                decimal soTien = 0;
                int thang = 0;
                int nam = 0;

                if (string.Equals(loai, "PhuCap", StringComparison.OrdinalIgnoreCase))
                {
                    maNV = cbPC.SelectedValue?.ToString();
                    moTa = tbNotePC.Text.Trim();
                    if (!decimal.TryParse(tbSoTienPC.Text.Trim(), out soTien))
                    {
                        MessageBox.Show("Số tiền phải là số hợp lệ!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        return;
                    }
                    thang = datePC.Value.Month;
                    nam = datePC.Value.Year;
                }
                else
                {
                    maNV = cbKT.SelectedValue?.ToString();
                    moTa = tbNoteKT.Text.Trim();
                    if (!decimal.TryParse(tbSoTienKT.Text.Trim(), out soTien))
                    {
                        MessageBox.Show("Số tiền phải là số hợp lệ!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        return;
                    }
                    thang = dateKT.Value.Month;
                    nam = dateKT.Value.Year;
                }

                AllowanceDeductionDTO dto = new AllowanceDeductionDTO(maNV, loai, moTa, soTien, thang, nam);
                dto.MaPhuCapKhoanTru = id;

                bool result = allowanceDeductionBLL.Update(dto);
                if (result)
                {
                    MessageBox.Show("Cập nhật thành công!", "Thành công", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    listAllowanceDeduction = allowanceDeductionBLL.GetAll();
                    dataPCKT.DataSource = null;
                    dataPCKT.DataSource = listAllowanceDeduction;
                }
                else
                {
                    MessageBox.Show("Cập nhật thất bại!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi khi cập nhật PCKT: " + ex.Message, "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btnCapNhatThuong_Click(object sender, EventArgs e)
        {
            try
            {
                if (dataThuong.CurrentRow == null)
                {
                    MessageBox.Show("Vui lòng chọn một dòng để cập nhật.", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }

                var row = dataThuong.CurrentRow;
                int maThuong = Convert.ToInt32(row.Cells["MaThuong"].Value);

                string maNV = cbThuong.SelectedValue?.ToString();
                string tenThuong = tbThuong.Text.Trim();
                decimal phanTram;
                if (!decimal.TryParse(tbMucThuong.Text.Trim(), out phanTram))
                {
                    MessageBox.Show("Phần trăm thưởng phải là số hợp lệ!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    return;
                }

                int thang = dateThuong.Value.Month;
                int nam = dateThuong.Value.Year;

                BonusDTO bonus = new BonusDTO(maNV, tenThuong, phanTram, thang, nam);
                bonus.MaThuong = maThuong;

                bool result = bonusBLL.UpdateBonus(bonus);
                if (result)
                {
                    MessageBox.Show("Cập nhật thưởng thành công!", "Thành công", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    listBonus = bonusBLL.GetAllBonuses();
                    dataThuong.DataSource = null;
                    dataThuong.DataSource = listBonus;
                }
                else
                {
                    MessageBox.Show("Cập nhật thưởng thất bại!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi khi cập nhật thưởng: " + ex.Message, "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btnCapNhatPC_Click(object sender, EventArgs e)
        {
            try
            {
                if (dataPCKT.CurrentRow == null)
                {
                    MessageBox.Show("Vui lòng chọn một dòng để cập nhật.", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }

                var row = dataPCKT.CurrentRow;
                int id = Convert.ToInt32(row.Cells["MaPhuCapKhoanTru"].Value);
                string loai = row.Cells["Loai"].Value?.ToString();

                string maNV = null;
                string moTa = null;
                decimal soTien = 0;
                int thang = 0;
                int nam = 0;

                maNV = cbPC.SelectedValue?.ToString();
                moTa = tbNotePC.Text.Trim();
                if (!decimal.TryParse(tbSoTienPC.Text.Trim(), out soTien))
                {
                    MessageBox.Show("Số tiền phải là số hợp lệ!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    return;
                }
                thang = datePC.Value.Month;
                nam = datePC.Value.Year;

                AllowanceDeductionDTO dto = new AllowanceDeductionDTO(maNV, loai, moTa, soTien, thang, nam);
                dto.MaPhuCapKhoanTru = id;

                bool result = allowanceDeductionBLL.Update(dto);
                if (result)
                {
                    MessageBox.Show("Cập nhật thành công!", "Thành công", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    listAllowanceDeduction = allowanceDeductionBLL.GetAll();
                    dataPCKT.DataSource = null;
                    dataPCKT.DataSource = listAllowanceDeduction;
                }
                else
                {
                    MessageBox.Show("Cập nhật thất bại!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi khi cập nhật PCKT: " + ex.Message, "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btnCapNhatKT_Click(object sender, EventArgs e)
        {
            try
            {
                if (dataPCKT.CurrentRow == null)
                {
                    MessageBox.Show("Vui lòng chọn một dòng để cập nhật.", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }

                var row = dataPCKT.CurrentRow;
                int id = Convert.ToInt32(row.Cells["MaPhuCapKhoanTru"].Value);
                string loai = row.Cells["Loai"].Value?.ToString();

                string maNV = null;
                string moTa = null;
                decimal soTien = 0;
                int thang = 0;
                int nam = 0;

                maNV = cbPC.SelectedValue?.ToString();
                moTa = tbNotePC.Text.Trim();
                if (!decimal.TryParse(tbSoTienPC.Text.Trim(), out soTien))
                {
                    MessageBox.Show("Số tiền phải là số hợp lệ!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    return;
                }
                thang = datePC.Value.Month;
                nam = datePC.Value.Year;

                AllowanceDeductionDTO dto = new AllowanceDeductionDTO(maNV, loai, moTa, soTien, thang, nam);
                dto.MaPhuCapKhoanTru = id;

                bool result = allowanceDeductionBLL.Update(dto);
                if (result)
                {
                    MessageBox.Show("Cập nhật thành công!", "Thành công", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    listAllowanceDeduction = allowanceDeductionBLL.GetAll();
                    dataPCKT.DataSource = null;
                    dataPCKT.DataSource = listAllowanceDeduction;
                }
                else
                {
                    MessageBox.Show("Cập nhật thất bại!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi khi cập nhật PCKT: " + ex.Message, "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btnResetThuong_Click(object sender, EventArgs e)
        {
            try
            {
                tbThuong.Text = string.Empty;
                tbMucThuong.Text = string.Empty;

                var now = DateTime.Now;
                dateThuong.Value = new DateTime(now.Year, now.Month, 1);

                try
                {
                    cbThuong.SelectedIndex = -1;
                }
                catch
                {
                    cbThuong.SelectedItem = null;
                }
                if (dataThuong.SelectedRows != null && dataThuong.SelectedRows.Count > 0)
                    dataThuong.ClearSelection();
                if (dataThuong.CurrentCell != null)
                    dataThuong.CurrentCell = null;
            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi khi reset form thưởng: " + ex.Message, "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btnResetPCKT_Click(object sender, EventArgs e)
        {
            try
            {
                tbSoTienPC.Text = string.Empty;
                tbNotePC.Text = string.Empty;
                var now = DateTime.Now;
                datePC.Value = new DateTime(now.Year, now.Month, 1);
                try
                {
                    cbPC.SelectedIndex = -1;
                }
                catch
                {
                    cbPC.SelectedItem = null;
                }

                tbSoTienKT.Text = string.Empty;
                tbNoteKT.Text = string.Empty;
                dateKT.Value = new DateTime(now.Year, now.Month, 1);
                try
                {
                    cbKT.SelectedIndex = -1;
                }
                catch
                {
                    cbKT.SelectedItem = null;
                }

                if (dataPCKT.SelectedRows != null && dataPCKT.SelectedRows.Count > 0)
                    dataPCKT.ClearSelection();
                if (dataPCKT.CurrentCell != null)
                    dataPCKT.CurrentCell = null;
            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi khi reset form Phụ cấp/Khoản trừ: " + ex.Message, "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        /// <summary>
        /// Auto-generate:
        /// - Position allowance (PhuCap) based on employee position or base salary percent
        /// - Tax deduction (KhoanTru) = 5% of base salary
        /// - Absence deduction (KhoanTru) when employee worked less than expected hours in a month
        /// Inserts records using AllowanceDeductionBLL and refreshes the PCKT grid.
        /// </summary>
        private void GenerateAutoAllowancesAndDeductions(int month, int year)
        {
            if (month < 1 || month > 12) throw new ArgumentOutOfRangeException(nameof(month));
            if (year < 2000 || year > 2100) throw new ArgumentOutOfRangeException(nameof(year));

            try
            {
                listEmployee = employeeFullBLL.GetAllEmployees();
                listAllowanceDeduction = allowanceDeductionBLL.GetAll(); // current DB entries

                int inserted = 0;
                int skipped = 0;
                const int perMinutePenalty = 2000; // VND per minute

                foreach (var emp in listEmployee)
                {
                    if (string.IsNullOrWhiteSpace(emp.MaNhanVien)) continue;

                    // 1) Position allowance (PhuCap)
                    decimal positionPercent = GetPositionAllowancePercent(emp.ChucVu);
                    if (positionPercent > 0 && emp.MucLuong > 0)
                    {
                        decimal amount = Math.Round(emp.MucLuong * positionPercent, 0);
                        bool exists = listAllowanceDeduction.Any(x =>
                            x.MaNhanVien == emp.MaNhanVien &&
                            string.Equals(x.Loai, "PhuCap", StringComparison.OrdinalIgnoreCase) &&
                            string.Equals(x.MoTa, "Phu cấp chức vụ", StringComparison.OrdinalIgnoreCase) &&
                            x.ThangApDung == month && x.NamApDung == year);

                        if (!exists)
                        {
                            var dto = new AllowanceDeductionDTO(emp.MaNhanVien, "PhuCap", "Phu cấp chức vụ", amount, month, year);
                            if (allowanceDeductionBLL.Insert(dto)) { inserted++; listAllowanceDeduction.Add(dto); }
                        }
                        else skipped++;
                    }

                    // 2) Tax deduction 5%
                    decimal taxAmount = Math.Round(emp.MucLuong * 0.05m, 0);
                    bool taxExists = listAllowanceDeduction.Any(x =>
                        x.MaNhanVien == emp.MaNhanVien &&
                        string.Equals(x.Loai, "KhoanTru", StringComparison.OrdinalIgnoreCase) &&
                        string.Equals(x.MoTa, "Thuế TNCN 5%", StringComparison.OrdinalIgnoreCase) &&
                        x.ThangApDung == month && x.NamApDung == year);

                    if (!taxExists && taxAmount > 0)
                    {
                        var taxDto = new AllowanceDeductionDTO(emp.MaNhanVien, "KhoanTru", "Thuế TNCN 5%", taxAmount, month, year);
                        if (allowanceDeductionBLL.Insert(taxDto)) { inserted++; listAllowanceDeduction.Add(taxDto); }
                    }
                    else if (taxExists) skipped++;

                    // 3) Late/early deduction (keep this): total minutes late + early * perMinutePenalty
                    var attendanceTotal = attendanceBLL.calculateTotalOfMonth(emp.MaNhanVien, month, year);
                    int totalMinutesLateEarly = (attendanceTotal?.GoLate ?? 0) + (attendanceTotal?.LeaveEarly ?? 0);

                    if (totalMinutesLateEarly > 0)
                    {
                        decimal deductionAmount = Math.Round(totalMinutesLateEarly * (decimal)perMinutePenalty, 0);

                        bool existsLateEarly = listAllowanceDeduction.Any(x =>
                            x.MaNhanVien == emp.MaNhanVien &&
                            string.Equals(x.Loai, "KhoanTru", StringComparison.OrdinalIgnoreCase) &&
                            x.MoTa != null &&
                            x.MoTa.StartsWith("Trừ trễ/về sớm", StringComparison.OrdinalIgnoreCase) &&
                            x.ThangApDung == month && x.NamApDung == year);

                        if (!existsLateEarly && deductionAmount > 0)
                        {
                            var absDto = new AllowanceDeductionDTO(emp.MaNhanVien, "KhoanTru", $"Trừ trễ/về sớm ({totalMinutesLateEarly} phút)", deductionAmount, month, year);
                            if (allowanceDeductionBLL.Insert(absDto)) { inserted++; listAllowanceDeduction.Add(absDto); }
                        }
                        else skipped++;
                    }

                    // NOTE: intentionally do NOT create any "Trừ vắng" entries here.
                }

                // Refresh displayed list
                listAllowanceDeduction = allowanceDeductionBLL.GetAll();
                dataPCKT.DataSource = null;
                dataPCKT.DataSource = listAllowanceDeduction;

                MessageBox.Show($"Auto generation done. Inserted: {inserted}, Skipped(existing): {skipped}", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi khi tạo tự động PCKT/thuế: " + ex.Message, "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        /// <summary>
        /// Simple mapping from position title to allowance percent.
        /// Customize this mapping to match your business rules.
        /// Return decimal percent (e.g. 0.10m = 10%).
        /// </summary>
        private decimal GetPositionAllowancePercent(string chucVu)
        {
            if (string.IsNullOrWhiteSpace(chucVu)) return 0m;

            string normalized = chucVu.Trim().ToLowerInvariant();

            // Example rules — adapt to your org's policy
            if (normalized.Contains("giám đốc") || normalized.Contains("director") || normalized.Contains("giam doc")) return 0.20m;
            if (normalized.Contains("trưởng phòng") || normalized.Contains("manager") || normalized.Contains("truong phong")) return 0.10m;
            if (normalized.Contains("phó phòng") || normalized.Contains("pp") || normalized.Contains("pho phong")) return 0.07m;
            if (normalized.Contains("team lead") || normalized.Contains("lead")) return 0.06m;
            if (normalized.Contains("nhân viên") || normalized.Contains("staff") || normalized.Contains("nv")) return 0.03m;

            // Default fallback
            return 0.03m;
        }

        /// <summary>
        /// Example button handler (wire to a button on the form).
        /// Calls generator for month/year chosen from UI (use date pickers you already have).
        /// </summary>
        private void btnAutoGenerate_Click(object sender, EventArgs e)
        {
            // Use date controls already in your form (e.g., dateLocPCKT or datePC). Adjust if you have a specific picker.
            int month = dateLocPCKT.Value.Month;
            int year = dateLocPCKT.Value.Year;

            var confirm = MessageBox.Show($"Tạo tự động phụ cấp, khoản trừ và thuế cho {month:00}/{year}? (Sẽ bỏ qua mục đã tồn tại)", "Xác nhận", MessageBoxButtons.YesNo, MessageBoxIcon.Question);
            if (confirm == DialogResult.Yes)
            {
                GenerateAutoAllowancesAndDeductions(month, year);
            }
        }

        /// <summary>
        /// Run the DB work on a background thread, then refresh UI and show summary on the UI thread.
        /// Ensures generation runs once per month per app session (prevents duplicates and repeated prompts).
        /// </summary>
        private async void AutoGenerateForCurrentMonthIfNeeded()
        {
            string key = DateTime.Now.ToString("yyyyMM");
            if (_autoGeneratedMonths.Contains(key))
                return;

            // Mark now to avoid concurrent runs
            _autoGeneratedMonths.Add(key);

            int month = DateTime.Now.Month;
            int year = DateTime.Now.Year;

            try
            {
                // Run DB inserts on threadpool
                var result = await Task.Run(() => GenerateAutoAllowancesAndDeductionsInternal(month, year));

                // Refresh data and notify user on UI thread
                listAllowanceDeduction = allowanceDeductionBLL.GetAll();
                if (this.IsHandleCreated)
                {
                    this.Invoke((Action)(() =>
                    {
                        dataPCKT.DataSource = null;
                        dataPCKT.DataSource = listAllowanceDeduction;
                        MessageBox.Show($"Auto generation done. Inserted: {result.inserted}, Skipped(existing): {result.skipped}", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    }));
                }
            }
            catch (Exception ex)
            {
                if (this.IsHandleCreated)
                {
                    this.Invoke((Action)(() =>
                    {
                        MessageBox.Show("Lỗi khi tạo tự động PCKT/thuế: " + ex.Message, "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }));
                }
            }
        }

        /// <summary>
        /// Database-only logic: inserts allowances/deductions. Returns (inserted, skipped).
        /// Does NOT touch UI controls or show message boxes so it can run on a background thread.
        /// </summary>
        private (int inserted, int skipped) GenerateAutoAllowancesAndDeductionsInternal(int month, int year)
        {
            if (month < 1 || month > 12) throw new ArgumentOutOfRangeException(nameof(month));
            if (year < 2000 || year > 2100) throw new ArgumentOutOfRangeException(nameof(year));

            int inserted = 0;
            int skipped = 0;
            const int perMinutePenalty = 2000; // VND per minute

            // Load fresh lists from BLL/DAO
            var employees = employeeFullBLL.GetAllEmployees();
            var existingPCKT = allowanceDeductionBLL.GetAll();

            foreach (var emp in employees)
            {
                if (string.IsNullOrWhiteSpace(emp.MaNhanVien)) continue;

                // 1) Position allowance (PhuCap)
                decimal positionPercent = GetPositionAllowancePercent(emp.ChucVu);
                if (positionPercent > 0 && emp.MucLuong > 0)
                {
                    decimal amount = Math.Round(emp.MucLuong * positionPercent, 0);
                    bool exists = existingPCKT.Any(x =>
                        x.MaNhanVien == emp.MaNhanVien &&
                        string.Equals(x.Loai, "PhuCap", StringComparison.OrdinalIgnoreCase) &&
                        string.Equals(x.MoTa, "Phu cấp chức vụ", StringComparison.OrdinalIgnoreCase) &&
                        x.ThangApDung == month && x.NamApDung == year);

                    if (!exists)
                    {
                        var dto = new AllowanceDeductionDTO(emp.MaNhanVien, "PhuCap", "Phu cấp chức vụ", amount, month, year);
                        if (allowanceDeductionBLL.Insert(dto))
                        {
                            inserted++;
                            existingPCKT.Add(dto);
                        }
                    }
                    else skipped++;
                }

                // 2) Tax deduction 5%
                decimal taxAmount = Math.Round(emp.MucLuong * 0.05m, 0);
                bool taxExists = existingPCKT.Any(x =>
                    x.MaNhanVien == emp.MaNhanVien &&
                    string.Equals(x.Loai, "KhoanTru", StringComparison.OrdinalIgnoreCase) &&
                    string.Equals(x.MoTa, "Thuế TNCN 5%", StringComparison.OrdinalIgnoreCase) &&
                    x.ThangApDung == month && x.NamApDung == year);

                if (!taxExists && taxAmount > 0)
                {
                    var taxDto = new AllowanceDeductionDTO(emp.MaNhanVien, "KhoanTru", "Thuế TNCN 5%", taxAmount, month, year);
                    if (allowanceDeductionBLL.Insert(taxDto))
                    {
                        inserted++;
                        existingPCKT.Add(taxDto);
                    }
                }
                else if (taxExists) skipped++;

                // 3) Late/early deduction only (per-minute)
                var attendanceTotal = attendanceBLL.calculateTotalOfMonth(emp.MaNhanVien, month, year);
                int totalMinutesLateEarly = (attendanceTotal?.GoLate ?? 0) + (attendanceTotal?.LeaveEarly ?? 0);

                if (totalMinutesLateEarly > 0)
                {
                    decimal deductionAmount = Math.Round(totalMinutesLateEarly * (decimal)perMinutePenalty, 0);

                    bool existsLateEarly = existingPCKT.Any(x =>
                        x.MaNhanVien == emp.MaNhanVien &&
                        string.Equals(x.Loai, "KhoanTru", StringComparison.OrdinalIgnoreCase) &&
                        x.MoTa != null &&
                        x.MoTa.StartsWith("Trừ trễ/về sớm", StringComparison.OrdinalIgnoreCase) &&
                        x.ThangApDung == month && x.NamApDung == year);

                    if (!existsLateEarly && deductionAmount > 0)
                    {
                        var absDto = new AllowanceDeductionDTO(emp.MaNhanVien, "KhoanTru", $"Trừ trễ/về sớm ({totalMinutesLateEarly} phút)", deductionAmount, month, year);
                        if (allowanceDeductionBLL.Insert(absDto))
                        {
                            inserted++;
                            existingPCKT.Add(absDto);
                        }
                    }
                    else skipped++;
                }

                // Intentionally do NOT create any "Trừ vắng" / missing-hours deductions here.
            }

            return (inserted, skipped);
        }
    }
}
